---
# tasks file for instance
- name: create a instance
  gcp_compute_instance:
      state: present
      name: "{{name}}"
      machine_type: n1-standard-1
      disks:
        - auto_delete: false
          boot: true
          source: "{{ disk }}"
      network_interfaces:
          - access_configs:
              - name: 'External NAT'
                type: 'ONE_TO_ONE_NAT'
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
  register: instance


- name: extracting IP
  debug:
      var: instance.networkInterfaces[0].networkIP


- name: Wait for SSH to come up
  wait_for: host={{ instance.networkInterfaces[0].networkIP }} port=22 delay=10 timeout=60

- name: Add host to groupname
  add_host: hostname={{ instance.networkInterfaces[0].networkIP }} groupname=new_instances
